apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fni4qjdhh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fni4qjdhh-go 
  name: fni4qjdhh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fni4qjdhh-go 
